// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3UF3tfjR_DPflFOakhcMABW5VWiDJKA',
    appId: '1:650291910582:web:005c342b865b3df1ce9317',
    messagingSenderId: '650291910582',
    projectId: 'gemini-goalkeeper-2024',
    authDomain: 'gemini-goalkeeper-2024.firebaseapp.com',
    storageBucket: 'gemini-goalkeeper-2024.appspot.com',
    measurementId: 'G-0XL8BP2D5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzC9IjFnq2VEMbSunGpYk3O-fGy6FwahQ',
    appId: '1:650291910582:android:77197afb25529e84ce9317',
    messagingSenderId: '650291910582',
    projectId: 'gemini-goalkeeper-2024',
    storageBucket: 'gemini-goalkeeper-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbpzovXzW55YLBqIFHfUQDbLFgSeqTGf8',
    appId: '1:650291910582:ios:c7ad38a2ad54d93ace9317',
    messagingSenderId: '650291910582',
    projectId: 'gemini-goalkeeper-2024',
    storageBucket: 'gemini-goalkeeper-2024.appspot.com',
    iosBundleId: 'com.example.geminiProactFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbpzovXzW55YLBqIFHfUQDbLFgSeqTGf8',
    appId: '1:650291910582:ios:c7ad38a2ad54d93ace9317',
    messagingSenderId: '650291910582',
    projectId: 'gemini-goalkeeper-2024',
    storageBucket: 'gemini-goalkeeper-2024.appspot.com',
    iosBundleId: 'com.example.geminiProactFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3UF3tfjR_DPflFOakhcMABW5VWiDJKA',
    appId: '1:650291910582:web:005c342b865b3df1ce9317',
    messagingSenderId: '650291910582',
    projectId: 'gemini-goalkeeper-2024',
    authDomain: 'gemini-goalkeeper-2024.firebaseapp.com',
    storageBucket: 'gemini-goalkeeper-2024.appspot.com',
    measurementId: 'G-0XL8BP2D5W',
  );
}
